In [16]:
# Import pandas library
import pandas as pd

In [17]:
dataset=pd.read_csv("CKD.csv")
dataset=pd.get_dummies(dataset, drop_first=True).astype(int)
dataset

,age,bp,al,su,bgr,bu,sc,sod,pot,hrmo,...,pc_normal,pcc_present,ba_present,htn_yes,dm_yes,cad_yes,appet_yes,pe_yes,ane_yes,classification_yes
0,2,76,3,0,148,57,3,137,4,12,...,0,0,0,0,0,0,1,1,0,1
1,3,76,2,0,148,22,0,137,4,10,...,1,0,0,0,0,0,1,0,0,1
2,4,76,1,0,99,23,0,138,4,12,...,1,0,0,0,0,0,1,0,0,1
3,5,76,1,0,148,16,0,138,3,8,...,1,0,0,0,0,0,1,0,1,1
4,5,50,0,0,148,25,0,137,4,11,...,1,0,0,0,0,0,1,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,51,70,0,0,219,36,1,139,3,12,...,1,0,0,0,0,0,1,0,0,1
395,51,70,0,2,220,68,2,137,4,8,...,1,0,0,1,1,0,1,0,1,1
396,51,70,3,0,110,115,6,134,2,9,...,1,0,0,1,1,0,0,0,0,1
397,51,90,0,0,207,80,6,142,5,8,...,1,0,0,1,1,0,1,0,1,1
398,51,80,0,0,100,49,1,140,5,16,...,1,0,0,0,0,0,1,0,0,0

In [18]:
dataset[["classification_yes"]].value_counts()

classification_yes
1                     249
0                     150
Name: count, dtype: int64

In [19]:
dataset.columns

Index(['age', 'bp', 'al', 'su', 'bgr', 'bu', 'sc', 'sod', 'pot', 'hrmo', 'pcv',
       'wc', 'rc', 'sg_b', 'sg_c', 'sg_d', 'sg_e', 'rbc_normal', 'pc_normal',
       'pcc_present', 'ba_present', 'htn_yes', 'dm_yes', 'cad_yes',
       'appet_yes', 'pe_yes', 'ane_yes', 'classification_yes'],
      dtype='object')

In [20]:
independent=dataset[['age', 'bp', 'al', 'su', 'bgr', 'bu', 'sc', 'sod', 'pot', 'hrmo', 'pcv',
       'wc', 'rc', 'sg_b', 'sg_c', 'sg_d', 'sg_e', 'rbc_normal', 'pc_normal',
       'pcc_present', 'ba_present', 'htn_yes', 'dm_yes', 'cad_yes',
       'appet_yes', 'pe_yes', 'ane_yes']]
independent

,age,bp,al,su,bgr,bu,sc,sod,pot,hrmo,...,rbc_normal,pc_normal,pcc_present,ba_present,htn_yes,dm_yes,cad_yes,appet_yes,pe_yes,ane_yes
0,2,76,3,0,148,57,3,137,4,12,...,1,0,0,0,0,0,0,1,1,0
1,3,76,2,0,148,22,0,137,4,10,...,1,1,0,0,0,0,0,1,0,0
2,4,76,1,0,99,23,0,138,4,12,...,1,1,0,0,0,0,0,1,0,0
3,5,76,1,0,148,16,0,138,3,8,...,1,1,0,0,0,0,0,1,0,1
4,5,50,0,0,148,25,0,137,4,11,...,1,1,0,0,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,51,70,0,0,219,36,1,139,3,12,...,1,1,0,0,0,0,0,1,0,0
395,51,70,0,2,220,68,2,137,4,8,...,1,1,0,0,1,1,0,1,0,1
396,51,70,3,0,110,115,6,134,2,9,...,1,1,0,0,1,1,0,0,0,0
397,51,90,0,0,207,80,6,142,5,8,...,1,1,0,0,1,1,0,1,0,1
398,51,80,0,0,100,49,1,140,5,16,...,1,1,0,0,0,0,0,1,0,0

In [21]:
dependent=dataset['classification_yes']
dependent

0      1
1      1
2      1
3      1
4      1
      ..
394    1
395    1
396    1
397    1
398    0
Name: classification_yes, Length: 399, dtype: int64

In [22]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test=train_test_split(independent, dependent, test_size=1/3, random_state=0)

In [23]:
from sklearn.svm import SVC
classifier = SVC(kernel = 'rbf', random_state = 0)
classifier=classifier.fit(X_train, Y_train)

In [24]:
Y_pred=classifier.predict(X_test) #Predict Y for the X_test

In [25]:
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(Y_test,Y_pred)
print(cm)

[[ 0 51]
 [ 0 82]]

In [26]:
from sklearn.metrics import classification_report
clf_report=classification_report(Y_test, Y_pred)
print(clf_report)

              precision    recall  f1-score   support

           0       0.00      0.00      0.00        51
           1       0.62      1.00      0.76        82

    accuracy                           0.62       133
   macro avg       0.31      0.50      0.38       133
weighted avg       0.38      0.62      0.47       133

C:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
C:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
C:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

In [27]:
X_test

,age,bp,al,su,bgr,bu,sc,sod,pot,hrmo,...,rbc_normal,pc_normal,pcc_present,ba_present,htn_yes,dm_yes,cad_yes,appet_yes,pe_yes,ane_yes
132,46,70,0,0,100,47,0,142,3,16,...,1,1,0,0,0,0,0,1,0,0
309,66,90,2,0,153,76,3,137,4,12,...,1,1,0,1,0,0,0,0,0,0
334,69,70,0,0,83,42,1,139,3,16,...,1,1,0,0,0,0,0,1,0,0
196,55,100,1,4,297,53,2,139,4,11,...,1,1,0,0,1,1,0,1,0,0
246,60,90,2,0,105,53,2,136,5,11,...,0,1,0,0,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
349,71,70,0,0,81,18,0,145,5,14,...,1,1,0,0,0,0,0,1,0,0
168,50,80,0,0,137,46,0,139,5,14,...,1,1,0,0,0,0,0,1,0,0
150,48,100,0,0,103,79,5,135,6,6,...,1,1,0,0,1,0,1,0,0,0
392,51,60,3,0,148,34,1,137,4,10,...,0,0,0,0,0,0,0,1,0,0
66,34,60,0,0,91,49,1,135,4,13,...,1,1,0,0,0,0,0,1,0,0

In [33]:
X_test.iloc[-1], Y_test.iloc[-1]

(age              34
 bp               60
 al                0
 su                0
 bgr              91
 bu               49
 sc                1
 sod             135
 pot               4
 hrmo             13
 pcv              48
 wc             8600
 rc                4
 sg_b              0
 sg_c              0
 sg_d              0
 sg_e              0
 rbc_normal        1
 pc_normal         1
 pcc_present       0
 ba_present        0
 htn_yes           0
 dm_yes            0
 cad_yes           0
 appet_yes         1
 pe_yes            0
 ane_yes           0
 Name: 66, dtype: int64,
 np.int64(0))

In [32]:
pred_svm_op=classifier.predict([[34,64,0,0,91,49,1,135,4,13,48,8600,4,0,0,0,0,1,1,0,0,0,0,0,1,0,0]]) 
pred_svm_op

C:\Anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but SVC was fitted with feature names
  warnings.warn(

array([1])

In [36]:
X_test,Y_test

(     age   bp  al  su  bgr  bu  sc  sod  pot  hrmo  ...  rbc_normal  \
 132   46   70   0   0  100  47   0  142    3    16  ...           1
 309   66   90   2   0  153  76   3  137    4    12  ...           1
 334   69   70   0   0   83  42   1  139    3    16  ...           1
 196   55  100   1   4  297  53   2  139    4    11  ...           1
 246   60   90   2   0  105  53   2  136    5    11  ...           0
 ..   ...  ...  ..  ..  ...  ..  ..  ...  ...   ...  ...         ...
 349   71   70   0   0   81  18   0  145    5    14  ...           1
 168   50   80   0   0  137  46   0  139    5    14  ...           1
 150   48  100   0   0  103  79   5  135    6     6  ...           1
 392   51   60   3   0  148  34   1  137    4    10  ...           0
 66    34   60   0   0   91  49   1  135    4    13  ...           1

      pc_normal  pcc_present  ba_present  htn_yes  dm_yes  cad_yes  appet_yes  \
 132          1            0           0        0       0        0          1
 309          1            0           1        0       0        0          0
 334          1            0           0        0       0        0          1
 196          1            0           0        1       1        0          1
 246          1            0           0        0       0        0          1
 ..         ...          ...         ...      ...     ...      ...        ...
 349          1            0           0        0       0        0          1
 168          1            0           0        0       0        0          1
 150          1            0           0        1       0        1          0
 392          0            0           0        0       0        0          1
 66           1            0           0        0       0        0          1

      pe_yes  ane_yes
 132       0        0
 309       0        0
 334       0        0
 196       0        0
 246       0        0
 ..      ...      ...
 349       0        0
 168       0        0
 150       0        0
 392       0        0
 66        0        0

 [133 rows x 27 columns],
 132    0
 309    1
 334    0
 196    1
 246    1
       ..
 349    0
 168    0
 150    1
 392    1
 66     0
 Name: classification_yes, Length: 133, dtype: int64)